server:
  port: 8003

spring:
  application:
    name: short-link-aggregation
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}   # 本地没设环境变量时用默认值
  producer:
    group: short-link-stats-producer


aggregation:
  remote-url: http://127.0.0.1:${server.port}

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: false
    time-window: 1
    max-access-count: 20
  bloom:
    expected-insertions: 100000000
    false-probability: 0.001
    rebuild:
      enabled: true
      cron: "0 0 3 * * ?"        # 每天凌晨 3 点

  domain:
    default: nurl.ink:8003
  mq-topic: short-link-stats
  demo-mode:
    enable: false
    blacklist:
      - /api/short-link/admin/v1/group
      - /api/short-link/admin/v1/recycle-bin/remove
      - /api/short-link/admin/v1/create
      - /api/short-link/admin/v1/create/batch
      - /api/short-link/admin/v1/update
      - /api/short-link/admin/v1/user
      - /api/short-link/admin/v1/user/logout
      - /api/short-link/admin/v1/recycle-bin/save
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
