server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:127.0.0.1:9876}   # 本地没设环境变量时用默认值
  producer:
    group: short-link-stats-producer


short-link:
  domain:
    default: nurl.ink:8001
  mq-topic: short-link-stats

  bloom:
    expected-insertions: 100000000
    false-probability: 0.001
    rebuild:
      enabled: true
      cron: "0 0 3 * * ?"        # 每天凌晨 3 点

  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
